---
title: "iterations and listcols"
author: "Youssra Yemmas"
date: "2023-10-31"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(rvest)
knitr::opts_chunk$set(echo = TRUE)
set.seed(1)
```

```{r}
vec_numeric = 1:4
vec_char = c("My", "name", "is", "Youssra ")

tibble(
  num = vec_numeric,
  char = vec_char
)
vec_logical = c(TRUE, TRUE, TRUE, FALSE)
```

```{r}
l =
  list(
    vec_numeric = 1:5,
vec_char = LETTERS,
matrix = matrix(1:10, nrow = 5, ncol = 2),
summary = summary(rnorm(100))
  )

```

# Accessing lists
```{r}

l$vec_char
l[[2]]
l[["summary"]]
```

### Loops
```{r}
list_norm_samples = 
  list(
    a = rnorm(20, 1, 5),
    b = rnorm(20, 0, 7),
    c = rnorm(20, 20, 1),
    d = rnorm(20, -45, 13)
  )
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("You need at lease 2 numbers to get z scores")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x,
    sd = sd_x
  )
}
```
```{r}
mean_and_sd(list_norm_samples$a)
mean_and_sd(list_norm_samples$b)
mean_and_sd(list_norm_samples$c)
mean_and_sd(list_norm_samples$d)
```


```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  
  output[[i]] = mean_and_sd(list_norm_samples[[i]])
  
}
output

```

