---
title: "writing_functions"
author: "Youssra Yemmas"
date: "2023-10-26"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(knitr)
knitr::opts_chunk$set(echo = TRUE)

```

Set seed for reproducibility
```{r}
set.seed(12345)

```

### Z score function

Z scores dubtract the mean and divide by the sd
```{r}
x_vec = rnorm(20, mean = 5, sd = .3)
```

Compute Z scores for 'x_vec'.

```{r}
(x_vec - mean(x_vec)) / sd(x_vec)
```


Write a function to do this

```{r}
z_score = function(x) {
  
  if (!is.numeric(x)) {
    stop("Arguement should be numbers")
  } else if (length(x) < 2) {
    stop("You need at least 2 numbers to get z scores")
  }
  
  z = (x - mean(x)) / sd(x)
  
  
  z
  
}
```

Check that this works

```{r}
z_score(x = x_vec)


z_score(x = rnorm(10, mean = 5))
```

Keep checking.

```{r error=FALSE, include=FALSE}
#z_score(x = 3)


#z_score(c("my", "name", "is", "Youssra"))


#z_score(c(TRUE, TRUE, FALSE, TRUE))

#z_score(iris)
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  list(mean = mean_x, 
       sd = sd_x
       )
}

```

Double check
```{r}
mean_and_sd(x_vec)
```

### Start getting means and sds
```{r}

x_vec = rnorm(n = 30, mean = 5, sd = .5)

tibble(
  mean = mean(x_vec),
  sd = sd(x_vec)
)
```

Let's write a function that uses 'n' , a true mean and true SD as inputs

```{r}
sim_mean_sd = function(n_obs, mu, sigma) {
  
  x_vec = rnorm(n = n_obs, mean = mu, sd = sigma)

tibble(
  mean = mean(x_vec),
  sd = sd(x_vec)
)
}

sim_mean_sd(n_obs = 30, mu = 5, sigma = .5)

sim_mean_sd(12, 24, 4) #positional matching 
```

```{r}
fellowship_ring =
  readxl::read_excel("./LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "fellowship_wing") %>% 
  janitor::clean_names()

lotr_load_and_tidy = function(path = "./LotR_Words.xlsx", cell_range, movie_name) {
  
  movie_df = 
    readxl::read_excel(path, range = cell_range) |>
    janitor::clean_names() |>
    gather(key = sex, value = words, female:male) |>
    mutate(race = str_to_lower(race),
           movie = movie_name) 
    #pivot_longer(
      #female:male,
      #names_to = "sex",
      #values_to = "words"
    #) can do pivot longer as well 
  
  movie_df
  
}

lotr_tidy = 
  bind_rows(
    lotr_load_and_tidy("./LotR_Words.xlsx", "B3:D6", "fellowship_ring"),
    lotr_load_and_tidy("./LotR_Words.xlsx", "F3:H6", "two_towers"),
    lotr_load_and_tidy("./LotR_Words.xlsx", "J3:L6", "return_king")) |>
  select(movie, everything()) 
```


### NSDUH


```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

data_marj = 
  nsduh_html |> 
  html_table() |> 
  nth(1) |>
  slice(-1) |> 
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)) |>
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))


```


Try to write a quick function.

```{r}
nsduh_import = function(html, table_number, outcome_name){
  
  html |> 
  html_table() |> 
  nth(table_number) |>
  slice(-1) |> 
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent),
    outcome = outcome_name) |>
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
  
}

nsduh_import(html = nsduh_html, table_number = 1, outcome_name = "marj")
nsduh_import(html = nsduh_html, table_number = 4, outcome_name = "cocaine")

```
